const Themes = {
	Acer : 0,
	Aztec : 1,
	BitTile : 2,
	Camellia : 3,
	Charcoal : 4,
	CopperFlame : 5, 
	Cranberry : 6,
	DarkSquare : 7,
	DarkTile : 8,
	DenimDaisies : 9,
	HoldFast : 10,
	Invaders : 11,
	LavaRock : 12,
	LeopardSkin : 13,
	OctoRedux : 14,
	Ohno : 15,
	Parker : 16,
	PokerTable : 17,
	PozneLato : 18,
	PumpkinPeak : 19,
	Renzler : 20,
	RubySundial : 21,
	SandBlossom : 22,
	Seventies : 23,
	SoftGrid : 24,
	StandIn : 25,
	StrawFlowers : 26,
	SubtleWood : 27,
	UpwardClimb : 28,
	VioletFabric : 29
}

const ThemeStyles = [
	{
		BackgroundImage : 'acer.gif',
		HandInfoBgColor : '#004C05',
		ButtonBgColor : '#003503',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 1,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#002602',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#004C05',
		Name : 'Acer',
		Owned : false,
		PriceInGold : 2,
		TitleBgColor : '#005405',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#004C05'
	},
	{
		BackgroundImage : 'aztec.gif',
		HandInfoBgColor : '#1E1E1E',
		ButtonBgColor : '#1A1A1A',
		ButtonFgColor : '#DDFF00',
		GameNoAlpha : 1,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#DDFF00',
		LevelBgColor : '#131313',
		LevelFgColor : '#DDFF00',
		MiddleHandBgColor : '#1E1E1E',
		Name : 'Aztec',
		Owned : false,
		PriceInGold : 2,
		TitleBgColor : '#1E1E1E',
		TitleFgColor : '#DDFF00',
		TopHandBgColor : '#1E1E1E'
	},
	{
		BackgroundImage : 'bit-tile.gif',
		HandInfoBgColor : '#1C6D93',
		ButtonBgColor : '#1A6488',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 0.7,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#155471',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#1C6D93',
		Name : 'Bit Tile',
		Owned : false,
		PriceInGold : 0,
		TitleBgColor : '#1E759E',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#1C6D93'
	},
	{
		BackgroundImage : 'camellia.gif',
		HandInfoBgColor : '#233F28',
		ButtonBgColor : '#1C3320',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 0.7,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#152618',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#233F28',
		Name : 'Camellia',
		Owned : false,
		PriceInGold : 3,
		TitleBgColor : '#233F28',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#233F28'
	},
	{
		BackgroundImage : 'charcoal.gif',
		HandInfoBgColor : '#141414',
		ButtonBgColor : '#111111',
		ButtonFgColor : '#7F7F7F',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#7F7F7F',
		LevelBgColor : '#0C0C0C',
		LevelFgColor : '#7F7F7F',
		MiddleHandBgColor : '#141414',
		Name : 'Charcoal',
		Owned : false,
		PriceInGold : 2,
		TitleBgColor : '#141414',
		TitleFgColor : '#7F7F7F',
		TopHandBgColor : '#141414'
	},
	{
		BackgroundImage : 'copper-flame.gif',
		HandInfoBgColor : '#320900',
		ButtonBgColor : '#350900',
		ButtonFgColor : '#91EAE2',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#91EAE2',
		LevelBgColor : '#320900',
		LevelFgColor : '#91EAE2',
		MiddleHandBgColor : '#320900',
		Name : 'Copper Flame',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#380A00',
		TitleFgColor : '#91EAE2',
		TopHandBgColor : '#320900'
	},
	{
		BackgroundImage : 'cranberry.gif',
		HandInfoBgColor : '#3F0505',
		ButtonBgColor : '#390404',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#390404',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#3F0505',
		Name : 'Cranberry',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#3F0505',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#3F0505'
	},
	{
		BackgroundImage : 'dark-square.gif',
		HandInfoBgColor : '#141414',
		ButtonBgColor : '#111111',
		ButtonFgColor : '#7F7F7F',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#7F7F7F',
		LevelBgColor : '#0C0C0C',
		LevelFgColor : '#7F7F7F',
		MiddleHandBgColor : '#141414',
		Name : 'Dark Square',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#141414',
		TitleFgColor : '#7F7F7F',
		TopHandBgColor : '#141414'
	},
	{
		BackgroundImage : 'dark-tile.gif',
		HandInfoBgColor : '#3F3835',
		ButtonBgColor : '#443F3D',
		ButtonFgColor : '#BABABA',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#BABABA',
		LevelBgColor : '#333333',
		LevelFgColor : '#BABABA',
		MiddleHandBgColor : '#3F3835',
		Name : 'Dark Tile',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#4C4442',
		TitleFgColor : '#BABABA',
		TopHandBgColor : '#3F3835'
	},
	{
		BackgroundImage : 'denim-daisies.gif',
		HandInfoBgColor : '#9F2E53',
		ButtonBgColor : '#B3345E',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 0.8,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#9F2E53',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#9F2E53',
		Name : 'Denim Daisies',
		Owned : false,
		PriceInGold : 2,
		TitleBgColor : '#C63A68',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#9F2E53'
	},
	{
		BackgroundImage : 'hold-fast.gif',
		HandInfoBgColor : '#702E08',
		ButtonBgColor : '#7E3409',
		ButtonFgColor : '#DBAA75',
		GameNoAlpha : 0.8,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#DBAA75',
		LevelBgColor : '#702E08',
		LevelFgColor : '#DBAA75',
		MiddleHandBgColor : '#702E08',
		Name : 'Hold Fast',
		Owned : false,
		PriceInGold : 3,
		TitleBgColor : '#8C3A0A',
		TitleFgColor : '#DBAA75',
		TopHandBgColor : '#702E08'
	},
	{
		BackgroundImage : 'invaders.gif',
		HandInfoBgColor : '#430A0A',
		ButtonBgColor : '#4B0B0B',
		ButtonFgColor : '#E53333',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#E53333',
		LevelBgColor : '#430A0A',
		LevelFgColor : '#E53333',
		MiddleHandBgColor : '#430A0A',
		Name : 'Invaders',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#540C0C',
		TitleFgColor : '#E53333',
		TopHandBgColor : '#430A0A'
	},
	{
		BackgroundImage : 'lava-rock.gif',
		HandInfoBgColor : '#380000',
		ButtonBgColor : '#320000',
		ButtonFgColor : '#E53333',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#E53333',
		TitleFgColor : '#E53333',
		LevelBgColor : '#320000',
		LevelFgColor : '#E53333',
		MiddleHandBgColor : '#380000',
		Name : 'Lava Rock',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#380000',
		TopHandBgColor : '#380000'
	},
	{
		BackgroundImage : 'leopard-skin.gif',
		HandInfoBgColor : '#241419',
		ButtonBgColor : '#26151A',
		ButtonFgColor : '#897C56',
		GameNoAlpha : 1,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#897C56',
		LevelBgColor : '#241419',
		LevelFgColor : '#897C56',
		MiddleHandBgColor : '#241419',
		Name : 'Leopard Skin',
		Owned : false,
		PriceInGold : 2,
		TitleBgColor : '#28161C',
		TitleFgColor : '#897C56',
		TopHandBgColor : '#241419'
	},
	{
		BackgroundImage : 'octo-redux.gif',
		HandInfoBgColor : '#534D41',
		ButtonBgColor : '#534D41',
		ButtonFgColor : '#AF9E66',
		GameNoAlpha : 1,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#AF9E66',
		LevelBgColor : '#494339',
		LevelFgColor : '#AF9E66',
		MiddleHandBgColor : '#534D41',
		Name : 'Octo Redux',
		Owned : false,
		PriceInGold : 3,
		TitleBgColor : '#686051',
		TitleFgColor : '#AF9E66',
		TopHandBgColor : '#534D41'
	},
	{
		BackgroundImage : 'ohno.gif',
		HandInfoBgColor : '#283028',
		ButtonBgColor : '#283028',
		ButtonFgColor : '#FC4444',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FC4444',
		LevelBgColor : '#111416',
		LevelFgColor : '#FC4444',
		MiddleHandBgColor : '#283028',
		Name : 'Ohno',
		Owned : false,
		PriceInGold : 2,
		TitleBgColor : '#303028',
		TitleFgColor : '#FC4444',
		TopHandBgColor : '#283028'
	},
	{
		BackgroundImage : 'parker.gif',
		HandInfoBgColor : '#303949',
		ButtonBgColor : '#303949',
		ButtonFgColor : '#C9BCB2',
		GameNoAlpha : 1,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#C9BCB2',
		LevelBgColor : '#2A3140',
		LevelFgColor : '#C9BCB2',
		MiddleHandBgColor : '#303949',
		Name : 'Parker',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#3D475B',
		TitleFgColor : '#C9BCB2',
		TopHandBgColor : '#303949'
	},
	{
		BackgroundImage : 'poker-table.gif',
		HandInfoBgColor : '#002804',
		ButtonBgColor : '#002303',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#001902',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#002804',
		Name : 'Poker Table',
		Owned : false,
		PriceInGold : 0,
		TitleBgColor : '#002804',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#002804'
	},
	{
		BackgroundImage : 'pozne-lato.gif',
		HandInfoBgColor : '#002740',
		ButtonBgColor : '#002943',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 1,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#002740',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#002740',
		Name : 'Pozne Lato',
		Owned : false,
		PriceInGold : 2,
		TitleBgColor : '#002B47',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#002740'
	},
	{
		BackgroundImage : 'pumpkin-peak.gif',
		HandInfoBgColor : '#CE663A',
		ButtonBgColor : '#C1592D',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 0.7,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#B54C21',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#C96035',
		Name : 'Pumpkin Peak',
		Owned : false,
		PriceInGold : 2,
		TitleBgColor : '#FF8754',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#CE663A'
	},
	{
		BackgroundImage : 'renzler.gif',
		HandInfoBgColor : '#201612',
		ButtonBgColor : '#201612',
		ButtonFgColor : '#6D5647',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#6D5647',
		LevelBgColor : '#1C1310',
		LevelFgColor : '#6D5647',
		MiddleHandBgColor : '#201612',
		Name : 'Renzler',
		Owned : false,
		PriceInGold : 2,
		TitleBgColor : '#281C16',
		TitleFgColor : '#6D5647',
		TopHandBgColor : '#201612'
	},
	{
		BackgroundImage : 'ruby-sundial.gif',
		HandInfoBgColor : '#6B0026',
		ButtonBgColor : '#87002D',
		ButtonFgColor : '#F796B5',
		GameNoAlpha : 1,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#F796B5',
		LevelBgColor : '#6B0026',
		LevelFgColor : '#F796B5',
		MiddleHandBgColor : '#6B0026',
		Name : 'Ruby Sundial',
		Owned : false,
		PriceInGold : 3,
		TitleBgColor : '#C11449',
		TitleFgColor : '#F796B5',
		TopHandBgColor : '#6B0026'
	},
	{
		BackgroundImage : 'sand-blossom.gif',
		HandInfoBgColor : '#686351',
		ButtonBgColor : '#736D59',
		ButtonFgColor : '#E0D8BF',
		GameNoAlpha : 1,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#E0D8BF',
		LevelBgColor : '#686351',
		LevelFgColor : '#E0D8BF',
		MiddleHandBgColor : '#686351',
		Name : 'Sand Blossom',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#7D7761',
		TitleFgColor : '#E0D8BF',
		TopHandBgColor : '#686351'
	},
	{
		BackgroundImage : '70s.gif',
		HandInfoBgColor : '#B5AD7A',
		ButtonBgColor : '#9E976B',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 1,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#716C4C',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#B5AD7A',
		Name : 'Seventies',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#B5AD7A',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#B5AD7A'
	},
	{
		BackgroundImage : 'soft-grid.gif',
		HandInfoBgColor : '#005B79',
		ButtonBgColor : '#006485',
		ButtonFgColor : '#FFFFFF',
		GameNoAlpha : 0.7,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#FFFFFF',
		LevelBgColor : '#005B79',
		LevelFgColor : '#FFFFFF',
		MiddleHandBgColor : '#005B79',
		Name : 'Soft Grid',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#006E91',
		TitleFgColor : '#FFFFFF',
		TopHandBgColor : '#005B79'
	},
	{
		BackgroundImage : 'stand-in.gif',
		HandInfoBgColor : '#2A2A2A',
		ButtonBgColor : '#2D2D2D',
		ButtonFgColor : '#A88C1E',
		GameNoAlpha : 0.7,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#A88C1E',
		LevelBgColor : '#2A2A2A',
		LevelFgColor : '#A88C1E',
		MiddleHandBgColor : '#2A2A2A',
		Name : 'Stand-In',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#303030',
		TitleFgColor : '#A88C1E',
		TopHandBgColor : '#2A2A2A'
	},
	{
		BackgroundImage : 'straw-flowers.gif',
		HandInfoBgColor : '#5F3F4F',
		ButtonBgColor : '#694656',
		ButtonFgColor : '#E2DDC9',
		GameNoAlpha : 0.8,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#E2DDC9',
		LevelBgColor : '#5F3F4F',
		LevelFgColor : '#E2DDC9',
		MiddleHandBgColor : '#5F3F4F',
		Name : 'Straw Flowers',
		Owned : false,
		PriceInGold : 0,
		TitleBgColor : '#724C5E',
		TitleFgColor : '#E2DDC9',
		TopHandBgColor : '#5F3F4F'
	},
	{
		BackgroundImage : 'subtle-wood.gif',
		HandInfoBgColor : '#34160B',
		ButtonBgColor : '#37180C',
		ButtonFgColor : '#B26042',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#B26042',
		LevelBgColor : '#34160B',
		LevelFgColor : '#B26042',
		MiddleHandBgColor : '#34160B',
		Name : 'Subtle Wood',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#3A190C',
		TitleFgColor : '#B26042',
		TopHandBgColor : '#34160B'
	},
	{
		BackgroundImage : 'upward-climb.gif',
		HandInfoBgColor : '#161402',
		ButtonBgColor : '#181502',
		ButtonFgColor : '#4C8EAF',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#4C8EAF',
		LevelBgColor : '#161402',
		LevelFgColor : '#4C8EAF',
		MiddleHandBgColor : '#161402',
		Name : 'Upward Climb',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#191602',
		TitleFgColor : '#4C8EAF',
		TopHandBgColor : '#161402'
	},
	{
		BackgroundImage : 'violet-fabric.gif',
		HandInfoBgColor : '#312A36',
		ButtonBgColor : '#362E3C',
		ButtonFgColor : '#9387A0',
		GameNoAlpha : 0.5,
		GameNoFgColor : '#FFFFFF',
		HandInfoFgColor : '#9387A0',
		LevelBgColor : '#312A36',
		LevelFgColor : '#9387A0',
		MiddleHandBgColor : '#312A36',
		Name : 'Violet Fabric',
		Owned : false,
		PriceInGold : 1,
		TitleBgColor : '#3B3241',
		TitleFgColor : '#9387A0',
		TopHandBgColor : '#312A36'
	}
];

class Theme {
	constructor () {
		this.playerID = null;
		this.themes = [];
		this.themeNames = [];
		this.levelBgColor = 0;
		this.levelFgColor = 0;
		this.titleBgColor = 0;
		this.titleFgColor = 0;
		this.buttonBgColor = 0;
		this.buttonFgColor = 0;
		this.topHandInfoBgColor = 0;
		this.middleHandInfoBgColor = 0;
		this.backHandInfoBgColor = 0;
		this.handInfoFgColor;
		this.gameNoColor = 0;
		this.gameNoAlpha = 0;
		this.bgImageFile = "";
		this.priceInGold = 0;
	}
}
